// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * LoadAppConfig 加载配置
 */
export function LoadAppConfig(): $CancellablePromise<$models.AppConfig | null> {
    return $Call.ByID(2291801473).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ReloadAppConfig 重新加载配置文件信息,会刷新当前实例配置字段
 */
export function ReloadAppConfig(): $CancellablePromise<$models.AppConfig | null> {
    return $Call.ByID(837796534).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SaveAppConfig 保存配置并刷新
 */
export function SaveAppConfig(config: $models.AppConfig): $CancellablePromise<void> {
    return $Call.ByID(3558405774, config);
}

// Private type creation functions
const $$createType0 = $models.AppConfig.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
