// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AiConfig {
    "ApiKey": string;
    "Model": string;
    "BaseUrl": string;

    /** Creates a new AiConfig instance. */
    constructor($$source: Partial<AiConfig> = {}) {
        if (!("ApiKey" in $$source)) {
            this["ApiKey"] = "";
        }
        if (!("Model" in $$source)) {
            this["Model"] = "";
        }
        if (!("BaseUrl" in $$source)) {
            this["BaseUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AiConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AiConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AiConfig($$parsedSource as Partial<AiConfig>);
    }
}

export class AppConfig {
    "App": AppMeta;
    "Window": WindowConfig;
    "Ai": AiConfig;

    /** Creates a new AppConfig instance. */
    constructor($$source: Partial<AppConfig> = {}) {
        if (!("App" in $$source)) {
            this["App"] = (new AppMeta());
        }
        if (!("Window" in $$source)) {
            this["Window"] = (new WindowConfig());
        }
        if (!("Ai" in $$source)) {
            this["Ai"] = (new AiConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AppConfig {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("App" in $$parsedSource) {
            $$parsedSource["App"] = $$createField0_0($$parsedSource["App"]);
        }
        if ("Window" in $$parsedSource) {
            $$parsedSource["Window"] = $$createField1_0($$parsedSource["Window"]);
        }
        if ("Ai" in $$parsedSource) {
            $$parsedSource["Ai"] = $$createField2_0($$parsedSource["Ai"]);
        }
        return new AppConfig($$parsedSource as Partial<AppConfig>);
    }
}

export class AppMeta {
    "Name": string;
    "Version": string;

    /** Creates a new AppMeta instance. */
    constructor($$source: Partial<AppMeta> = {}) {
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Version" in $$source)) {
            this["Version"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppMeta instance from a string or object.
     */
    static createFrom($$source: any = {}): AppMeta {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppMeta($$parsedSource as Partial<AppMeta>);
    }
}

export class WindowConfig {
    "Width": number;
    "Height": number;
    "X": string;
    "Y": string;

    /** Creates a new WindowConfig instance. */
    constructor($$source: Partial<WindowConfig> = {}) {
        if (!("Width" in $$source)) {
            this["Width"] = 0;
        }
        if (!("Height" in $$source)) {
            this["Height"] = 0;
        }
        if (!("X" in $$source)) {
            this["X"] = "";
        }
        if (!("Y" in $$source)) {
            this["Y"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): WindowConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowConfig($$parsedSource as Partial<WindowConfig>);
    }
}

// Private type creation functions
const $$createType0 = AppMeta.createFrom;
const $$createType1 = WindowConfig.createFrom;
const $$createType2 = AiConfig.createFrom;
