// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class R<T> {
    "success": boolean;
    "code": number;
    "data": T | null;
    "message": string;

    /** Creates a new R instance. */
    constructor($$source: Partial<R<T>> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }
        if (!("code" in $$source)) {
            this["code"] = 0;
        }
        if (!("data" in $$source)) {
            this["data"] = null;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Given creation functions for each type parameter,
     * returns a creation function for a concrete instance
     * of the generic class R.
     */
    static createFrom<T = any>($$createParamT: (source: any) => T): ($$source?: any) => R<T> {
        const $$createField2_0 = $$createType0($$createParamT);
        return ($$source: any = {}) => {
            let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
            if ("data" in $$parsedSource) {
                $$parsedSource["data"] = $$createField2_0($$parsedSource["data"]);
            }
            return new R<T>($$parsedSource as Partial<R<T>>);
        };
    }
}

// Private type creation functions
const $$createType0 = ($$createParamT: any) => $Create.Nullable($$createParamT);
