// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as common$0 from "../../pkg/common/models.js";

/**
 * Chat 执行非流式对话，并在返回前完成基础参数校验。
 */
export function Chat(req: models$0.AiChatRequest): $CancellablePromise<common$0.R<models$0.AiChatResponse>> {
    return $Call.ByID(3974881973, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ChatStream 发起流式对话，返回 sessionId 给前端订阅事件流。
 */
export function ChatStream(req: models$0.AiChatRequest): $CancellablePromise<common$0.R<string>> {
    return $Call.ByID(1935376021, req).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetChatSessionDetail 返回指定会话的历史消息。
 */
export function GetChatSessionDetail(sessionId: string): $CancellablePromise<common$0.R<models$0.AiChatSessionDetail>> {
    return $Call.ByID(278209700, sessionId).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ListChatSessions 返回最近活跃的历史会话。
 */
export function ListChatSessions(limit: number): $CancellablePromise<common$0.R<models$0.AiChatSessionSummary[]>> {
    return $Call.ByID(1740989668, limit).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * ListModels 返回配置页与聊天页可选模型列表。
 */
export function ListModels(): $CancellablePromise<common$0.R<models$0.AiModelListResponse>> {
    return $Call.ByID(419682009).then(($result: any) => {
        return $$createType9($result);
    });
}

// Private type creation functions
const $$createType0 = models$0.AiChatResponse.createFrom;
const $$createType1 = common$0.R.createFrom($$createType0);
const $$createType2 = common$0.R.createFrom($Create.Any);
const $$createType3 = models$0.AiChatSessionDetail.createFrom;
const $$createType4 = common$0.R.createFrom($$createType3);
const $$createType5 = models$0.AiChatSessionSummary.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = common$0.R.createFrom($$createType6);
const $$createType8 = models$0.AiModelListResponse.createFrom;
const $$createType9 = common$0.R.createFrom($$createType8);
