// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as common$0 from "../../pkg/common/models.js";

export function AddTaskCateGory(taskCategory: models$0.TaskCategoryModel): $CancellablePromise<common$0.R<string>> {
    return $Call.ByID(1010930112, taskCategory).then(($result: any) => {
        return $$createType0($result);
    });
}

export function DeleteTaskCateGory(key: string): $CancellablePromise<common$0.R<string>> {
    return $Call.ByID(3054155388, key).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetTaskCategoryList(name: string): $CancellablePromise<common$0.R<models$0.TaskCategoryModel[]>> {
    return $Call.ByID(2586881807, name).then(($result: any) => {
        return $$createType3($result);
    });
}

export function SaveOrUpdateTaskCateGory(taskCategory: models$0.TaskCategoryModel): $CancellablePromise<common$0.R<string>> {
    return $Call.ByID(3362988446, taskCategory).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SaveTaskCateGory(taskCategory: models$0.TaskCategoryModel[]): $CancellablePromise<common$0.R<string>> {
    return $Call.ByID(3254327662, taskCategory).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = common$0.R.createFrom($Create.Any);
const $$createType1 = models$0.TaskCategoryModel.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = common$0.R.createFrom($$createType2);
