// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as common$0 from "../../pkg/common/models.js";

export function DoubleClickTitleBar(): $CancellablePromise<common$0.R<string>> {
    return $Call.ByID(2247504442).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = common$0.R.createFrom($Create.Any);
