// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * AiChatHistoryMessage 历史会话中的单条消息。
 */
export class AiChatHistoryMessage {
    "role": string;
    "content": string;
    "reasoningContent"?: string | null;
    "model"?: string;
    "usage"?: AiUsage | null;
    "durationMs"?: number | null;
    "firstTokenMs"?: number | null;
    "modelStats"?: AiModelStats | null;
    "error"?: string;

    /** Creates a new AiChatHistoryMessage instance. */
    constructor($$source: Partial<AiChatHistoryMessage> = {}) {
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AiChatHistoryMessage instance from a string or object.
     */
    static createFrom($$source: any = {}): AiChatHistoryMessage {
        const $$createField4_0 = $$createType1;
        const $$createField7_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("usage" in $$parsedSource) {
            $$parsedSource["usage"] = $$createField4_0($$parsedSource["usage"]);
        }
        if ("modelStats" in $$parsedSource) {
            $$parsedSource["modelStats"] = $$createField7_0($$parsedSource["modelStats"]);
        }
        return new AiChatHistoryMessage($$parsedSource as Partial<AiChatHistoryMessage>);
    }
}

/**
 * AiChatMessage 前端传入的聊天消息
 */
export class AiChatMessage {
    /**
     * system / user / assistant
     */
    "role": string;

    /**
     * 消息内容
     */
    "content": string;

    /** Creates a new AiChatMessage instance. */
    constructor($$source: Partial<AiChatMessage> = {}) {
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AiChatMessage instance from a string or object.
     */
    static createFrom($$source: any = {}): AiChatMessage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AiChatMessage($$parsedSource as Partial<AiChatMessage>);
    }
}

/**
 * AiChatRequest 前端发起的对话请求
 */
export class AiChatRequest {
    "messages": AiChatMessage[];

    /**
     * 可选，覆盖默认模型
     */
    "model"?: string;

    /**
     * 可选
     */
    "temperature"?: number | null;

    /**
     * 可选
     */
    "maxTokens"?: number | null;

    /**
     * 是否流式
     */
    "stream": boolean;

    /**
     * single / compare
     */
    "mode"?: string;

    /**
     * 流式会话标识
     */
    "sessionId"?: string;

    /**
     * 同轮对比问题标识
     */
    "roundId"?: string;

    /** Creates a new AiChatRequest instance. */
    constructor($$source: Partial<AiChatRequest> = {}) {
        if (!("messages" in $$source)) {
            this["messages"] = [];
        }
        if (!("stream" in $$source)) {
            this["stream"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AiChatRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): AiChatRequest {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField0_0($$parsedSource["messages"]);
        }
        return new AiChatRequest($$parsedSource as Partial<AiChatRequest>);
    }
}

/**
 * AiChatResponse 非流式对话完整响应
 */
export class AiChatResponse {
    "content": string;
    "reasoningContent"?: string | null;
    "model": string;
    "usage": AiUsage;
    "durationMs": number;
    "firstTokenMs"?: number | null;
    "modelStats"?: AiModelStats | null;

    /** Creates a new AiChatResponse instance. */
    constructor($$source: Partial<AiChatResponse> = {}) {
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("usage" in $$source)) {
            this["usage"] = (new AiUsage());
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AiChatResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): AiChatResponse {
        const $$createField3_0 = $$createType0;
        const $$createField6_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("usage" in $$parsedSource) {
            $$parsedSource["usage"] = $$createField3_0($$parsedSource["usage"]);
        }
        if ("modelStats" in $$parsedSource) {
            $$parsedSource["modelStats"] = $$createField6_0($$parsedSource["modelStats"]);
        }
        return new AiChatResponse($$parsedSource as Partial<AiChatResponse>);
    }
}

/**
 * AiChatSessionDetail 会话详情。
 */
export class AiChatSessionDetail {
    "sessionId": string;
    "messages": AiChatHistoryMessage[];

    /** Creates a new AiChatSessionDetail instance. */
    constructor($$source: Partial<AiChatSessionDetail> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("messages" in $$source)) {
            this["messages"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AiChatSessionDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): AiChatSessionDetail {
        const $$createField1_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField1_0($$parsedSource["messages"]);
        }
        return new AiChatSessionDetail($$parsedSource as Partial<AiChatSessionDetail>);
    }
}

/**
 * AiChatSessionSummary 会话列表摘要。
 */
export class AiChatSessionSummary {
    "sessionId": string;
    "title": string;
    "preview"?: string;
    "model"?: string;
    "roundCount": number;
    "promptTokens": number;
    "completionTokens": number;
    "totalTokens": number;
    "avgDurationMs": number;
    "avgFirstTokenMs": number;
    "lastActiveTime": string;

    /** Creates a new AiChatSessionSummary instance. */
    constructor($$source: Partial<AiChatSessionSummary> = {}) {
        if (!("sessionId" in $$source)) {
            this["sessionId"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("roundCount" in $$source)) {
            this["roundCount"] = 0;
        }
        if (!("promptTokens" in $$source)) {
            this["promptTokens"] = 0;
        }
        if (!("completionTokens" in $$source)) {
            this["completionTokens"] = 0;
        }
        if (!("totalTokens" in $$source)) {
            this["totalTokens"] = 0;
        }
        if (!("avgDurationMs" in $$source)) {
            this["avgDurationMs"] = 0;
        }
        if (!("avgFirstTokenMs" in $$source)) {
            this["avgFirstTokenMs"] = 0;
        }
        if (!("lastActiveTime" in $$source)) {
            this["lastActiveTime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AiChatSessionSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): AiChatSessionSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AiChatSessionSummary($$parsedSource as Partial<AiChatSessionSummary>);
    }
}

/**
 * AiModelListResponse 模型列表响应，支持回退状态提示。
 */
export class AiModelListResponse {
    "models": AiModelOption[];
    "fallback": boolean;
    "message"?: string;

    /** Creates a new AiModelListResponse instance. */
    constructor($$source: Partial<AiModelListResponse> = {}) {
        if (!("models" in $$source)) {
            this["models"] = [];
        }
        if (!("fallback" in $$source)) {
            this["fallback"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AiModelListResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): AiModelListResponse {
        const $$createField0_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField0_0($$parsedSource["models"]);
        }
        return new AiModelListResponse($$parsedSource as Partial<AiModelListResponse>);
    }
}

/**
 * AiModelOption 模型下拉选项。
 */
export class AiModelOption {
    "value": string;
    "label": string;
    "source"?: string;
    "available": boolean;
    "status"?: string;
    "hint"?: string;

    /** Creates a new AiModelOption instance. */
    constructor($$source: Partial<AiModelOption> = {}) {
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("available" in $$source)) {
            this["available"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AiModelOption instance from a string or object.
     */
    static createFrom($$source: any = {}): AiModelOption {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AiModelOption($$parsedSource as Partial<AiModelOption>);
    }
}

/**
 * AiModelStats 模型聚合统计信息。
 */
export class AiModelStats {
    "model": string;
    "totalCalls": number;
    "avgTokens": number;
    "avgFirstTokenMs": number;

    /** Creates a new AiModelStats instance. */
    constructor($$source: Partial<AiModelStats> = {}) {
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("totalCalls" in $$source)) {
            this["totalCalls"] = 0;
        }
        if (!("avgTokens" in $$source)) {
            this["avgTokens"] = 0;
        }
        if (!("avgFirstTokenMs" in $$source)) {
            this["avgFirstTokenMs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AiModelStats instance from a string or object.
     */
    static createFrom($$source: any = {}): AiModelStats {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AiModelStats($$parsedSource as Partial<AiModelStats>);
    }
}

/**
 * AiUsage 对话 token 用量统计。
 */
export class AiUsage {
    "promptTokens": number;
    "completionTokens": number;
    "totalTokens": number;

    /** Creates a new AiUsage instance. */
    constructor($$source: Partial<AiUsage> = {}) {
        if (!("promptTokens" in $$source)) {
            this["promptTokens"] = 0;
        }
        if (!("completionTokens" in $$source)) {
            this["completionTokens"] = 0;
        }
        if (!("totalTokens" in $$source)) {
            this["totalTokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AiUsage instance from a string or object.
     */
    static createFrom($$source: any = {}): AiUsage {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AiUsage($$parsedSource as Partial<AiUsage>);
    }
}

export class LocalResourceModel {
    "id": number | null;
    "valid": number;
    "sort": number | null;
    "createTime": time$0.Time | null;
    "modifyTime": time$0.Time | null;
    "name": string;
    "path": string | null;
    "type": string;
    "content": string;

    /** Creates a new LocalResourceModel instance. */
    constructor($$source: Partial<LocalResourceModel> = {}) {
        if (!("id" in $$source)) {
            this["id"] = null;
        }
        if (!("valid" in $$source)) {
            this["valid"] = 0;
        }
        if (!("sort" in $$source)) {
            this["sort"] = null;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = null;
        }
        if (!("modifyTime" in $$source)) {
            this["modifyTime"] = null;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = null;
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalResourceModel instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalResourceModel {
        const $$createField8_0 = $Create.ByteSlice;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("content" in $$parsedSource) {
            $$parsedSource["content"] = $$createField8_0($$parsedSource["content"]);
        }
        return new LocalResourceModel($$parsedSource as Partial<LocalResourceModel>);
    }
}

export class TaskCategoryModel {
    "id": number | null;
    "valid": number;
    "sort": number | null;
    "createTime": time$0.Time | null;
    "modifyTime": time$0.Time | null;
    "name": string;
    "key": string;
    "remark": string | null;
    "color": string | null;

    /** Creates a new TaskCategoryModel instance. */
    constructor($$source: Partial<TaskCategoryModel> = {}) {
        if (!("id" in $$source)) {
            this["id"] = null;
        }
        if (!("valid" in $$source)) {
            this["valid"] = 0;
        }
        if (!("sort" in $$source)) {
            this["sort"] = null;
        }
        if (!("createTime" in $$source)) {
            this["createTime"] = null;
        }
        if (!("modifyTime" in $$source)) {
            this["modifyTime"] = null;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("remark" in $$source)) {
            this["remark"] = null;
        }
        if (!("color" in $$source)) {
            this["color"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskCategoryModel instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskCategoryModel {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TaskCategoryModel($$parsedSource as Partial<TaskCategoryModel>);
    }
}

// Private type creation functions
const $$createType0 = AiUsage.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = AiModelStats.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = AiChatMessage.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = AiChatHistoryMessage.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = AiModelOption.createFrom;
const $$createType9 = $Create.Array($$createType8);
