// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"ic-wails/internal/api"
	"ic-wails/internal/config"
	"ic-wails/internal/core"
	"ic-wails/internal/repository"
	"ic-wails/internal/service"
)

// Injectors from wire.go:

func InitializeApp() *core.ApplicationHolder {
	applicationConfigManager := config.NewApplicationConfigManager()
	dataSource := repository.NewDataSource()
	aiChatRecordRepository := repository.NewAiChatRecordRepository(dataSource)
	aiModelCacheRepository := repository.NewAiModelCacheRepository(dataSource)
	aiChatService := service.NewAiChatService(applicationConfigManager, aiChatRecordRepository, aiModelCacheRepository)
	aiChatApi := api.NewAiChatApi(aiChatService)
	frontendNetApi := api.NewFrontendNetApi(aiChatApi)
	taskRepository := repository.NewTaskRepository(dataSource)
	taskCategoryService := service.NewTaskCategoryService(taskRepository)
	taskCategoryApi := api.NewTaskCategoryApi(taskCategoryService)
	windowManagerApi := api.NewWindowManagerApi()
	localResourceRepo := repository.NewLocalResourceRepo(dataSource)
	localResourceService := service.NewLocalResourceService(localResourceRepo)
	localResourceApi := api.NewLocalResourceApi(localResourceService)
	frontendApi := api.NewFrontendApi(taskCategoryApi, windowManagerApi, localResourceApi, aiChatApi, applicationConfigManager)
	applicationHolder := core.NewApplicationHolder(frontendNetApi, applicationConfigManager, frontendApi)
	return applicationHolder
}
